### PR TITLE
Printing QR with circles

### PR DESCRIPTION
**Pull request by btywoniuk**
Created ``style`` parameter.  
When set to ``circles`` change squares in the QR
to circles.

image

### CODE REVIEW

**Comment by mcroni** [comment]
thanks for this, its really awesome

**Comment by maribedran** [comment]
@btywoniuk I'll leave the same comment I made in #178 :

We recently merged #168 that adds a new image factory to allow adding color masks and different shapes. It introduces module drawers, responsible for drawing the shapes of the individual modules. Do you think this could be refactored into one of those module drawers? This approach allows a more flexible way of styling the QRs as the modules are pluggable and the main code doesn't have to be changed for each new format.

**Comment by SmileyChris** [comment]
This is doable with PIL images already and SVG in the upcoming 7.4 version.

**Comment by feavilan04** [comment]
where is version 7.4?

**Pull request closed without merging**
