### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by splash58**
add pdf factory

### CODE REVIEW

**Comment by heuer** [comment]
See https://github.com/lincolnloop/python-qrcode/pull/181#issuecomment-696343958

**Comment by splash58** [comment]
> See [#181 (comment)](https://github.com/lincolnloop/python-qrcode/pull/181#issuecomment-696343958)

**Comment by splash58** [comment]
> See [#181 (comment)](https://github.com/lincolnloop/python-qrcode/pull/181#issuecomment-696343958)
Pillow make pdf with image but not a vector content

**Comment by heuer** [comment]
> Pillow make pdf with image but not a vector content

On a first sight, without having studied the code in detail, #181 may be a better solution since it does not depend on external libraries.

**Comment by splash58** [comment]
> On a first sight, without having studied the code in detail, #181 may be a better solution since it does not depend on external libraries.

Seems, you are right. 
I really use own class to update template pdf by adding qr-code. But didn't  think to publish it while there are some good libraries for pdf processing

**Comment by maribedran** [comment]
This seems to be solved by the comment in #181 . @splash58 feel free to reopen this if you think it still adds necessary features.

**Pull request closed without merging**
